if [ "$TMUX" = "" ]; then tmux; fi

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

bindkey -v
setopt appendhistory
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt CORRECT_ALL

autoload -Uz compinit promptinit
compinit
promptinit

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^R' history-incremental-search-backward

eval $(dircolors)
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:approximate:*' max-errors 2
setopt COMPLETE_ALIASES
export CLICOLOR=1

PROMPT='%F{green}%n%f@%F{magenta}%m%f %F{blue}%B%~%b%f %# '
prompt agnoster

alias ls='ls --color=auto'
alias grep='grep --colour=auto'
